{
 "title": "Sensor System Status",
 "time": { "from": "now-7d", "to": "now" },
 "refresh": "15m",
 "templating": {
  "list": [
   { "name": "Sensor", "query": "show measurements" },
   { "name": "Measurement", "label": "Sensor", "query": "show measurements" }
  ]
 },
 "panels": [
  {
   "title": "Uptime",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "dtdurations" }
   ],
   "targets": [
    {
     "alias": "Uptime",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "/^$Sensor$/",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "key", "operator": "=", "value": "Uptime" }
     ]
    },
    {
     "alias": "Last OTA",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "/^$Sensor$/",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "key", "operator": "=", "value": "Last OTA" }
     ]
    }
   ]
  },
  {
   "title": "Messungen",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Anzahl",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "/^$Sensor$/",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "key", "operator": "=", "value": "Anzahl Messungen" }
     ]
    },
    {
     "alias": "Data Send Errors",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "/^$Sensor$/",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "key", "operator": "=", "value": "Data Send" },
      { "condition": "OR", "key": "key", "operator": "=", "value": "Data Send Errors" }
     ]
    }
   ]
  },
  {
   "title": "Free Memory",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Free Memory",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "/^$Sensor$/",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "key", "operator": "=", "value": "Free Memory" }
     ]
    },
    {
     "alias": "Heap Fragmentation",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "/^$Sensor$/",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "key", "operator": "=", "value": "Heap Fragmentation" }
     ]
    }
   ]
  },
  {
   "title": "Dauer Messübertragung",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "dtdurationms" }
   ],
   "targets": [
    {
     "alias": "Dauer Messübertragung",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "/^$Sensor$/",
     "query": "SELECT mean(\"value\") FROM /^$Sensor$/ WHERE (\"key\" = 'Dauer Messübertragung') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "key", "operator": "=", "value": "Dauer Messübertragung" }
     ]
    }
   ]
  },
  {
   "title": "Errors",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "SDS011",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "/^$Sensor$/",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "key", "operator": "=", "value": "SDS011 Errors" }
     ]
    },
    {
     "alias": "WiFi",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "/^$Sensor$/",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "key", "operator": "=", "value": "WiFi" },
      { "condition": "OR", "key": "key", "operator": "=", "value": "WiFi Errors" }
     ]
    }
   ]
  },
  {
   "title": "Reset Reasons",
   "type": "heatmap",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 14 },
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "key" ], "type": "tag" }
     ],
     "measurement": "/^$Sensor$/",
     "query": "SELECT count(/^[A-Z].*/) FROM /^$Sensor$/ WHERE (\"key\" = 'Reset Reason') AND $timeFilter GROUP BY time($__interval)",
     "select": [
      [
       { "params": [ "/^[A-Z].*/" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "key", "operator": "=", "value": "Reset Reason" }
     ]
    }
   ]
  },
  {
   "type": "bargauge",
   "gridPos": { "h": 2, "w": 12, "x": 12, "y": 19 },
   "targets": [
    {
     "alias": "Exception",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "measurement": "/^$Sensor$/",
     "query": "SELECT distinct(\"string\") FROM /^$Sensor$/ WHERE (\"key\" = 'Reset Reason') AND $timeFilter GROUP BY time($interval), \"key\"",
     "select": [
      [
       { "params": [ "Exception" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "key", "operator": "=", "value": "Reset Reason" }
     ]
    },
    {
     "alias": "Power On",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "measurement": "/^$Sensor$/",
     "query": "SELECT distinct(\"string\") FROM /^$Sensor$/ WHERE (\"key\" = 'Reset Reason') AND $timeFilter GROUP BY time($interval), \"key\"",
     "select": [
      [
       { "params": [ "Power on" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "key", "operator": "=", "value": "Reset Reason" }
     ]
    },
    {
     "alias": "External System",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "measurement": "/^$Sensor$/",
     "query": "SELECT distinct(\"string\") FROM /^$Sensor$/ WHERE (\"key\" = 'Reset Reason') AND $timeFilter GROUP BY time($interval), \"key\"",
     "select": [
      [
       { "params": [ "External System" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "key", "operator": "=", "value": "Reset Reason" }
     ]
    },
    {
     "alias": "Hardware Watchdog",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "measurement": "/^$Sensor$/",
     "query": "SELECT distinct(\"Hardware Watchdog\") FROM /^$Sensor$/ WHERE (\"key\" = 'Reset Reason') AND $timeFilter GROUP BY time($interval)",
     "select": [
      [
       { "params": [ "Hardware Watchdog" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "key", "operator": "=", "value": "Reset Reason" }
     ]
    },
    {
     "alias": "Software/System restart",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "measurement": "/^$Sensor$/",
     "query": "SELECT distinct(\"Software/System restart\") FROM /^$Sensor$/ WHERE (\"key\" = 'Reset Reason') AND $timeFilter GROUP BY time($interval)",
     "select": [
      [
       { "params": [ "Software/System restart" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "key", "operator": "=", "value": "Reset Reason" }
     ]
    }
   ]
  },
  {
   "title": "WiFi signal",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "dBm" }
   ],
   "targets": [
    {
     "alias": "WiFi signal",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "/^$Measurement$/",
     "select": [
      [
       { "params": [ "signal" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Samples",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 21 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "Samples",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "/^$Measurement$/",
     "select": [
      [
       { "params": [ "samples" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Max. Cycle",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "Max. Cycle",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "/^$Measurement$/",
     "select": [
      [
       { "params": [ "max_micro" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Min. Cycle",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 27 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "Min. Cycle",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "/^$Measurement$/",
     "select": [
      [
       { "params": [ "min_micro" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  }
 ]
}