{
 "title": "Sensor System Status",
 "time": { "from": "now-2d", "to": "now" },
 "refresh": "15m",
 "templating": {
  "list": [
   { "name": "Sensor", "query": "show measurements" },
   {
    "name": "INTL_NUMBER_OF_MEASUREMENTS",
    "query": "${VAR_INTL_NUMBER_OF_MEASUREMENTS}"
   },
   { "name": "INTL_TIME_SENDING_MS", "query": "${VAR_INTL_TIME_SENDING_MS}" },
   { "name": "INTL_ERROR", "query": "${VAR_INTL_ERROR}" },
   { "name": "INTL_DEVICE_STATUS", "query": "${VAR_INTL_DEVICE_STATUS}" },
   { "name": "Measurement", "label": "Sensor", "query": "show measurements" },
   {
    "name": "Node",
    "query": "SHOW TAG VALUES WITH KEY = node WHERE (_name =~ /^$Measurement$/)"
   },
   { "name": "Interval", "query": "${VAR_INTERVAL}" }
  ]
 },
 "panels": [
  {
   "title": "$INTL_DEVICE_STATUS",
   "type": "table",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "alias": "Firmware",
     "measurement": "/^$Sensor$/",
     "select": [
      [
       { "params": [ "string" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "key", "operator": "=", "value": "Firmware" }
     ]
    },
    {
     "alias": "Uptime",
     "measurement": "/^$Sensor$/",
     "select": [
      [
       { "params": [ "string" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "key", "operator": "=", "value": "Uptime" }
     ]
    },
    {
     "alias": "$INTL_NUMBER_OF_MEASUREMENTS",
     "measurement": "/^$Sensor$/",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      {
       "key": "key",
       "operator": "=~",
       "value": "/^$INTL_NUMBER_OF_MEASUREMENTS$/"
      }
     ]
    },
    {
     "alias": "NTP Info",
     "measurement": "/^$Sensor$/",
     "select": [
      [
       { "params": [ "string" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "key", "operator": "=", "value": "NTP Info" }
     ]
    },
    {
     "alias": "Last OTA",
     "measurement": "/^$Sensor$/",
     "select": [
      [
       { "params": [ "string" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "key", "operator": "=", "value": "Last OTA" }
     ]
    },
    {
     "alias": "Data Send Return",
     "measurement": "/^$Sensor$/",
     "select": [
      [
       { "params": [ "string" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "key", "operator": "=", "value": "Data Send Return" }
     ]
    },
    {
     "alias": "OTA Return",
     "measurement": "/^$Sensor$/",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "key", "operator": "=", "value": "OTA Return" }
     ]
    },
    {
     "alias": "OTA Return",
     "measurement": "/^$Sensor$/",
     "select": [
      [
       { "params": [ "string" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "key", "operator": "=", "value": "OTA Return" }
     ]
    }
   ]
  },
  {
   "title": "$INTL_ERROR",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "SDS011",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "/^$Sensor$/",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       {
        "params": [],
        "type": "non_negative_difference"
       }
      ]
     ],
     "tags": [
      { "key": "key", "operator": "=", "value": "SDS011 Errors" }
     ]
    },
    {
     "alias": "SPS30",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "/^$Sensor$/",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       {
        "params": [],
        "type": "non_negative_difference"
       }
      ]
     ],
     "tags": [
      { "key": "key", "operator": "=", "value": "Sensirion SPS30 Errors" }
     ]
    },
    {
     "alias": "WiFi",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "/^$Sensor$/",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       {
        "params": [],
        "type": "non_negative_difference"
       }
      ]
     ],
     "tags": [
      { "key": "key", "operator": "=", "value": "WiFi" },
      { "condition": "OR", "key": "key", "operator": "=", "value": "WiFi Errors" }
     ]
    },
    {
     "alias": "Data Send",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "/^$Sensor$/",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       {
        "params": [],
        "type": "non_negative_difference"
       }
      ]
     ],
     "tags": [
      { "key": "key", "operator": "=", "value": "Data Send Errors" }
     ]
    },
    {
     "alias": "InfluxDB",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "/^$Sensor$/",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       {
        "params": [],
        "type": "non_negative_difference"
       }
      ]
     ],
     "tags": [
      { "key": "key", "operator": "=", "value": "InfluxDB API" }
     ]
    },
    {
     "alias": "Madavi.de",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "/^$Sensor$/",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       {
        "params": [],
        "type": "non_negative_difference"
       }
      ]
     ],
     "tags": [
      { "key": "key", "operator": "=", "value": "Madavi.de API" }
     ]
    },
    {
     "alias": "Sensor.Community",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "/^$Sensor$/",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       {
        "params": [],
        "type": "non_negative_difference"
       }
      ]
     ],
     "tags": [
      { "key": "key", "operator": "=", "value": "Sensor.Community API" }
     ]
    },
    {
     "alias": "OpenSenseMap.org",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "/^$Sensor$/",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       {
        "params": [],
        "type": "non_negative_difference"
       }
      ]
     ],
     "tags": [
      { "key": "key", "operator": "=", "value": "OpenSenseMap.org API" }
     ]
    },
    {
     "alias": "Feinstaub-App",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "/^$Sensor$/",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       {
        "params": [],
        "type": "non_negative_difference"
       }
      ]
     ],
     "tags": [
      { "key": "key", "operator": "=", "value": "Feinstaub-App API" }
     ]
    },
    {
     "alias": "aircms.online",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "/^$Sensor$/",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       {
        "params": [],
        "type": "non_negative_difference"
       }
      ]
     ],
     "tags": [
      { "key": "key", "operator": "=", "value": "aircms.online API" }
     ]
    },
    {
     "alias": "Custom",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "/^$Sensor$/",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       {
        "params": [],
        "type": "non_negative_difference"
       }
      ]
     ],
     "tags": [
      { "key": "key", "operator": "=", "value": "Custom API" }
     ]
    }
   ]
  },
  {
   "title": "Memory",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "Free Memory",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "/^$Sensor$/",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "key", "operator": "=", "value": "Free Memory" }
     ]
    },
    {
     "alias": "Heap Fragmentation",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "/^$Sensor$/",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "key", "operator": "=", "value": "Heap Fragmentation" }
     ]
    }
   ]
  },
  {
   "title": "$INTL_TIME_SENDING_MS",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "alias": "$INTL_TIME_SENDING_MS",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "/^$Sensor$/",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "key", "operator": "=~", "value": "/^$INTL_TIME_SENDING_MS$/" }
     ]
    }
   ]
  },
  {
   "title": "Reset Reasons",
   "type": "heatmap",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 14 },
   "targets": [
    {
     "alias": "Power On",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "measurement": "/^$Sensor$/",
     "select": [
      [
       { "params": [ "string" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "key", "operator": "=", "value": "Reset Reason" },
      { "condition": "AND", "key": "string", "operator": "=~", "value": "/Power [Oo]n/" }
     ]
    },
    {
     "alias": "Software/System restart",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "/^$Sensor$/",
     "select": [
      [
       { "params": [ "string" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "key", "operator": "=", "value": "Reset Reason" },
      { "condition": "AND", "key": "string", "operator": "=", "value": "Software/System restart" }
     ]
    },
    {
     "alias": "Hardware Watchdog",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "/^$Sensor$/",
     "select": [
      [
       { "params": [ "string" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "key", "operator": "=", "value": "Reset Reason" },
      { "condition": "AND", "key": "string", "operator": "=", "value": "Hardware Watchdog" }
     ]
    },
    {
     "alias": "Exception",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "/^$Sensor$/",
     "select": [
      [
       { "params": [ "string" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "key", "operator": "=", "value": "Reset Reason" },
      { "condition": "AND", "key": "string", "operator": "=", "value": "Exception" }
     ]
    },
    {
     "alias": "External System",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "/^$Sensor$/",
     "select": [
      [
       { "params": [ "string" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "key", "operator": "=", "value": "Reset Reason" },
      { "condition": "AND", "key": "string", "operator": "=", "value": "External System" }
     ]
    },
    {
     "alias": "Software Watchdog",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "/^$Sensor$/",
     "select": [
      [
       { "params": [ "string" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "key", "operator": "=", "value": "Reset Reason" },
      { "condition": "AND", "key": "string", "operator": "=", "value": "Software Watchdog" }
     ]
    },
    {
     "alias": "Deep-Sleep Wake",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "/^$Sensor$/",
     "select": [
      [
       { "params": [ "string" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "key", "operator": "=", "value": "Reset Reason" },
      { "condition": "AND", "key": "string", "operator": "=", "value": "Deep-Sleep Wake" }
     ]
    }
   ]
  },
  {
   "title": "Web server response times",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "alias": "Connect",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "/^$Sensor$/",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "key", "operator": "=", "value": "curl-time-connect" }
     ]
    },
    {
     "alias": "Pre-transfer",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "/^$Sensor$/",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "key", "operator": "=", "value": "curl-time-pretransfer" }
     ]
    },
    {
     "alias": "Start transfer",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "/^$Sensor$/",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "key", "operator": "=", "value": "curl-time-starttransfer" }
     ]
    },
    {
     "alias": "Total time",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "/^$Sensor$/",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "key", "operator": "=", "value": "curl-time-total" }
     ]
    },
    {
     "alias": "Connection failed",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT last(\"value\") FROM /^$Sensor$/ WHERE (\"key\" = 'curl-time-connect' AND \"value\" = 0) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "WiFi signal",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "dBm" } },
   "targets": [
    {
     "alias": "WiFi signal",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "/^$Measurement$/",
     "select": [
      [
       { "params": [ "signal" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "node", "operator": "=~", "value": "/^$Node$/" }
     ]
    }
   ]
  },
  {
   "title": "Samples",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "Rate",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT mean(\"rate\") FROM (select \"samples\"/(\"interval\"/1000) AS \"rate\" FROM /^$Measurement$/ WHERE (\"node\" =~ /^$Node$/) AND $timeFilter) GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Min. Cycle",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "alias": "Min. Cycle",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "/^$Measurement$/",
     "select": [
      [
       { "params": [ "min_micro" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "node", "operator": "=~", "value": "/^$Node$/" }
     ]
    }
   ]
  },
  {
   "title": "Max. Cycle",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "alias": "Max. Cycle",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "/^$Measurement$/",
     "select": [
      [
       { "params": [ "max_micro" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "node", "operator": "=~", "value": "/^$Node$/" }
     ]
    }
   ]
  },
  {
   "title": "Firmware statistics",
   "type": "table",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "alias": "Sample Rate",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "/^$Measurement$/",
     "query": "SELECT \"rate\" FROM (select \"samples\"/(\"interval\"/1000) AS \"rate\" FROM /^$Measurement$/ WHERE (\"node\" =~ /^$Node$/) AND $timeFilter) ",
     "select": [
      [
       { "params": [ "samples/interval" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "node", "operator": "=~", "value": "/^$Node$/" }
     ]
    },
    {
     "alias": "Max. Cycle",
     "measurement": "/^$Measurement$/",
     "select": [
      [
       { "params": [ "max_micro" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "node", "operator": "=~", "value": "/^$Node$/" }
     ]
    },
    {
     "alias": "Min. Cycle",
     "measurement": "/^$Measurement$/",
     "select": [
      [
       { "params": [ "min_micro" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "node", "operator": "=~", "value": "/^$Node$/" }
     ]
    }
   ]
  },
  {
   "title": "Memory statistics",
   "type": "table",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "alias": "Free Memory",
     "measurement": "/^$Sensor$/",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "key", "operator": "=", "value": "Free Memory" }
     ]
    },
    {
     "alias": "Heap Fragmentation",
     "measurement": "/^$Sensor$/",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "key", "operator": "=", "value": "Heap Fragmentation" }
     ]
    }
   ]
  },
  {
   "title": "Web server performance statistics (seconds)",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "alias": "Connect",
     "measurement": "/^$Sensor$/",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "key", "operator": "=", "value": "curl-time-connect" },
      { "condition": "AND", "key": "value", "operator": ">", "value": "0" }
     ]
    },
    {
     "alias": "Pre-transfer",
     "measurement": "/^$Sensor$/",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "key", "operator": "=", "value": "curl-time-pretransfer" },
      { "condition": "AND", "key": "value", "operator": ">", "value": "0" }
     ]
    },
    {
     "alias": "Start transfer",
     "measurement": "/^$Sensor$/",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "key", "operator": "=", "value": "curl-time-starttransfer" },
      { "condition": "AND", "key": "value", "operator": ">", "value": "0" }
     ]
    },
    {
     "alias": "Time Total",
     "measurement": "/^$Sensor$/",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "key", "operator": "=", "value": "curl-time-total" },
      { "condition": "AND", "key": "value", "operator": ">", "value": "0" }
     ]
    },
    {
     "alias": "Errors",
     "measurement": "/^$Sensor$/",
     "select": [
      [
       { "params": [ "string" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "key", "operator": "=", "value": "curl-errormsg" }
     ]
    }
   ]
  },
  {
   "title": "$INTL_NUMBER_OF_MEASUREMENTS",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "$INTL_NUMBER_OF_MEASUREMENTS",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "/^$Sensor$/",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       {
        "params": [],
        "type": "non_negative_difference"
       }
      ]
     ],
     "tags": [
      {
       "key": "key",
       "operator": "=~",
       "value": "/^$INTL_NUMBER_OF_MEASUREMENTS$/"
      }
     ]
    }
   ]
  }
 ]
}