#!/bin/sh

# Definitions that can be used to unify results from firmware in
# other languages to German.
INTL_NUMBER_OF_MEASUREMENTS="Anzahl Messungen"
INTL_TIME_SENDING_MS="Dauer Messübertragung"
# Not (yet) used.
INTL_ERROR="Fehler"
INTL_DEVICE_STATUS="Gerätestatus"

# Pre-136-B2 definitions for all languages.
INTL_FREE_MEMORY="Free Memory"
INTL_HEAP_FRAGMENTATION="Heap Fragmentation"
INTL_LAST_OVER_THE_AIR="Last OTA"
INTL_UPTIME="Uptime"
INTL_RESET_REASON="Reset Reason"
INTL_DATA_SEND_RETURN_CODE="Data Send Return"
INTL_REACHABLE="reachable"
INTL_YES="Yes"
INTL_NO="No"

while read lang var string
do
   string=$(echo ${string} | tr -d \")
   case $var in
   # Scripts that can be used to unify measurement storage in one
   # specific language. Mainly to be used in testing environments
   # running firmware in different/changing languages. Use 'grep INTL'
   # on the output.
   INTL_NUMBER_OF_MEASUREMENTS)
       echo "        -e \"s/${string}/\${INTL_NUMBER_OF_MEASUREMENTS}/\" \\"
   ;;
   INTL_TIME_SENDING_MS)
       echo "        -e \"s/${string}/\${INTL_TIME_SENDING_MS}/\" \\"
   ;;
   # Scripts to 'untranslate' 136-B2+ additional translations to
   # preserve backwards compatibility with stored measurements and
   # grafana dashboards. Use 'grep ORIG' on the ouput.
   INTL_HEAP_FRAGMENTATION)
     [ "${string}" != "${INTL_HEAP_FRAGMENTATION}" ] && \
       echo "        -e \"s/${string}/\${ORIG_HEAP_FRAGMENTATION}/\" \\"
   ;;
   INTL_FREE_MEMORY)
     [ "${string}" != "${INTL_FREE_MEMORY}" ] && \
       echo "        -e \"s/${string}/\${ORIG_FREE_MEMORY}/\" \\"
   ;;
   INTL_LAST_OVER_THE_AIR)
     [ "${string}" != "${INTL_LAST_OVER_THE_AIR}" ] && \
       echo "        -e \"s/${string}/\${ORIG_LAST_OVER_THE_AIR}/\" \\"
   ;;
   INTL_UPTIME)
     [ "${string}" != "${INTL_UPTIME}" ] && \
       echo "        -e \"s/${string}/\${ORIG_UPTIME}/\" \\"
   ;;
   INTL_RESET_REASON)
     [ "${string}" != "${INTL_RESET_REASON}" ] && \
       echo "        -e \"s/${string}/\${ORIG_RESET_REASON}/\" \\"
   ;;
   INTL_DATA_SEND_RETURN_CODE)
     [ "${string}" != "${INTL_DATA_SEND_RETURN_CODE}" ] && \
       echo "        -e \"s/${string}/\${ORIG_DATA_SEND_RETURN_CODE}/\" \\"
   ;;
   INTL_REACHABLE)
     [ "${string}" != "${INTL_REACHABLE}" ] && \
       echo "        -e \"s/${string}/\${ORIG_REACHABLE}g/\" \\"
   ;;
   INTL_YES)
     [ "${string}" != "${INTL_YES}" ] && \
       echo "        -e \"s/: ${string}/: \${ORIG_YES}/g\" \\"
   ;;
   INTL_NO)
     [ "${string}" != "${INTL_NO}" ] && \
       echo "        -e \"s/: ${string}/: \${ORIG_NO}/g\" \\"
   ;;
   # Unused
   INTL_ERROR)
   ;;
   INTL_DEVICE_STATUS)
   ;;
   esac
done <<EOT | egrep -v '\[\[|\]\]'
bg INTL_DEVICE_STATUS "Статус на устройството"
bg INTL_ERROR "само грешки"
bg INTL_NUMBER_OF_MEASUREMENTS "Брой измервания"
bg INTL_TIME_SENDING_MS "Време, прекарано в изпращане"
bg INTL_DATA_SEND_RETURN_CODE "[[Data Send Return]]"
bg INTL_UPTIME "[[Uptime]]"
bg INTL_RESET_REASON "[[Reset Reason]]"
bg INTL_HEAP_FRAGMENTATION "[[Heap Fragmentation]]"
bg INTL_FREE_MEMORY "[[Free Memory]]"
bg INTL_LAST_OVER_THE_AIR "[[Last OTA]]"
br INTL_DEVICE_STATUS "Status do dispositivo"
br INTL_ERROR "erro"
br INTL_NUMBER_OF_MEASUREMENTS "Quantidade de medições"
br INTL_TIME_SENDING_MS "Duração de transmissão de medições"
br INTL_DATA_SEND_RETURN_CODE "[[Data Send Return]]"
br INTL_UPTIME "[[Uptime]]"
br INTL_RESET_REASON "[[Reset Reason]]"
br INTL_HEAP_FRAGMENTATION "[[Heap Fragmentation]]"
br INTL_FREE_MEMORY "[[Free Memory]]"
br INTL_LAST_OVER_THE_AIR "[[Last OTA]]"
cn INTL_DEVICE_STATUS "设备状态"
cn INTL_ERROR "唯恐有误"
cn INTL_NUMBER_OF_MEASUREMENTS "测量数量"
cn INTL_TIME_SENDING_MS "上传时间"
cn INTL_DATA_SEND_RETURN_CODE "[[Data Send Return]]"
cn INTL_UPTIME "[[Uptime]]"
cn INTL_RESET_REASON "[[Reset Reason]]"
cn INTL_HEAP_FRAGMENTATION "[[Heap Fragmentation]]"
cn INTL_FREE_MEMORY "[[Free Memory]]"
cn INTL_LAST_OVER_THE_AIR "[[Last OTA]]"
cz INTL_DEVICE_STATUS "Stav zařízení"
cz INTL_ERROR "chyba"
cz INTL_NUMBER_OF_MEASUREMENTS "Počet měření"
cz INTL_TIME_SENDING_MS "Doba nahrávání"
cz INTL_DATA_SEND_RETURN_CODE "[[Data Send Return]]"
cz INTL_UPTIME "[[Uptime]]"
cz INTL_RESET_REASON "[[Reset Reason]]"
cz INTL_HEAP_FRAGMENTATION "[[Heap Fragmentation]]"
cz INTL_FREE_MEMORY "[[Free Memory]]"
cz INTL_LAST_OVER_THE_AIR "[[Last OTA]]"
de INTL_DEVICE_STATUS "Gerätestatus"
de INTL_ERROR "Fehler"
de INTL_NUMBER_OF_MEASUREMENTS "Anzahl Messungen"
de INTL_TIME_SENDING_MS "Dauer Messübertragung"
de INTL_DATA_SEND_RETURN_CODE "Daten senden Return Code"
de INTL_UPTIME "Aktiv seit"
de INTL_RESET_REASON "Grund des Zurücksetzens"
de INTL_HEAP_FRAGMENTATION "Heap Fragmentierung"
de INTL_FREE_MEMORY "Freier Speicher"
de INTL_LAST_OVER_THE_AIR "Letztes OTA"
dk INTL_DEVICE_STATUS "Enhedsstatus"
dk INTL_ERROR "error"
dk INTL_NUMBER_OF_MEASUREMENTS "Antal målinger"
dk INTL_TIME_SENDING_MS "Tid brugt på afsendelse"
dk INTL_DATA_SEND_RETURN_CODE "[[Data Send Return]]"
dk INTL_UPTIME "[[Uptime]]"
dk INTL_RESET_REASON "[[Reset Reason]]"
dk INTL_HEAP_FRAGMENTATION "[[Heap Fragmentation]]"
dk INTL_FREE_MEMORY "[[Free Memory]]"
dk INTL_LAST_OVER_THE_AIR "[[Last OTA]]"
ee INTL_DEVICE_STATUS "Seadme olek"
ee INTL_ERROR "ainult vead"
ee INTL_NUMBER_OF_MEASUREMENTS "Mõõtmiste arv"
ee INTL_TIME_SENDING_MS "Üleslaadimisele kuluv aeg"
ee INTL_DATA_SEND_RETURN_CODE "[[Data Send Return]]"
ee INTL_UPTIME "[[Uptime]]"
ee INTL_RESET_REASON "[[Reset Reason]]"
ee INTL_HEAP_FRAGMENTATION "[[Heap Fragmentation]]"
ee INTL_FREE_MEMORY "[[Free Memory]]"
ee INTL_LAST_OVER_THE_AIR "[[Last OTA]]"
en INTL_DEVICE_STATUS "Device status"
en INTL_ERROR "only errors"
en INTL_NUMBER_OF_MEASUREMENTS "Number of measurements"
en INTL_TIME_SENDING_MS "Time spent uploading"
en INTL_DATA_SEND_RETURN_CODE "Data Send Return"
en INTL_UPTIME "Uptime"
en INTL_RESET_REASON "Reset Reason"
en INTL_HEAP_FRAGMENTATION "Heap Fragmentation"
en INTL_FREE_MEMORY "Free Memory"
en INTL_LAST_OVER_THE_AIR "Last OTA"
es INTL_DEVICE_STATUS "El estado del dispositivo"
es INTL_ERROR "Error"
es INTL_NUMBER_OF_MEASUREMENTS "Numero de mediciones"
es INTL_TIME_SENDING_MS "Tiempo empleado para enviar"
es INTL_DATA_SEND_RETURN_CODE "[[Data Send Return]]"
es INTL_UPTIME "[[Uptime]]"
es INTL_RESET_REASON "[[Reset Reason]]"
es INTL_HEAP_FRAGMENTATION "[[Heap Fragmentation]]"
es INTL_FREE_MEMORY "[[Free Memory]]"
es INTL_LAST_OVER_THE_AIR "[[Last OTA]]"
fi INTL_DEVICE_STATUS "Laitteen tila"
fi INTL_ERROR "vain virheet"
fi INTL_NUMBER_OF_MEASUREMENTS "Mittausten lukumäärä"
fi INTL_TIME_SENDING_MS "Lataamiseen käytetty aika"
fi INTL_DATA_SEND_RETURN_CODE "[[Data Send Return]]"
fi INTL_UPTIME "[[Uptime]]"
fi INTL_RESET_REASON "[[Reset Reason]]"
fi INTL_HEAP_FRAGMENTATION "[[Heap Fragmentation]]"
fi INTL_FREE_MEMORY "[[Free Memory]]"
fi INTL_LAST_OVER_THE_AIR "[[Last OTA]]"
fr INTL_DEVICE_STATUS "Etat de l'appareil"
fr INTL_ERROR "erreur"
fr INTL_NUMBER_OF_MEASUREMENTS "Nombre de mesures"
fr INTL_TIME_SENDING_MS "Durée de la transmission des mesures"
fr INTL_DATA_SEND_RETURN_CODE "[[Data Send Return]]"
fr INTL_UPTIME "[[Uptime]]"
fr INTL_RESET_REASON "[[Reset Reason]]"
fr INTL_HEAP_FRAGMENTATION "[[Heap Fragmentation]]"
fr INTL_FREE_MEMORY "[[Free Memory]]"
fr INTL_LAST_OVER_THE_AIR "[[Last OTA]]"
gr INTL_DEVICE_STATUS "Κατάσταση συσκευής"
gr INTL_ERROR "μόνο σφάλματα"
gr INTL_NUMBER_OF_MEASUREMENTS "Αριθμός μετρήσεων"
gr INTL_TIME_SENDING_MS "Χρόνος μεταφόρτωσης"
gr INTL_DATA_SEND_RETURN_CODE "[[Data Send Return]]"
gr INTL_UPTIME "[[Uptime]]"
gr INTL_RESET_REASON "[[Reset Reason]]"
gr INTL_HEAP_FRAGMENTATION "[[Heap Fragmentation]]"
gr INTL_FREE_MEMORY "[[Free Memory]]"
gr INTL_LAST_OVER_THE_AIR "[[Last OTA]]"
hr INTL_DEVICE_STATUS "Status uređaja"
hr INTL_ERROR "greške"
hr INTL_NUMBER_OF_MEASUREMENTS "Broj mjerenja"
hr INTL_TIME_SENDING_MS "Vrijeme utrošeno na slanje podataka"
hr INTL_DATA_SEND_RETURN_CODE "[[Data Send Return]]"
hr INTL_UPTIME "[[Uptime]]"
hr INTL_RESET_REASON "[[Reset Reason]]"
hr INTL_HEAP_FRAGMENTATION "[[Heap Fragmentation]]"
hr INTL_FREE_MEMORY "[[Free Memory]]"
hr INTL_LAST_OVER_THE_AIR "[[Last OTA]]"
hu INTL_DEVICE_STATUS "Eszköz státusz"
hu INTL_ERROR "csak hibajelzések"
hu INTL_NUMBER_OF_MEASUREMENTS "Mérések száma:"
hu INTL_TIME_SENDING_MS "Feltöltéssel töltött idő:"
hu INTL_DATA_SEND_RETURN_CODE "[[Data Send Return]]"
hu INTL_UPTIME "[[Uptime]]"
hu INTL_RESET_REASON "[[Reset Reason]]"
hu INTL_HEAP_FRAGMENTATION "[[Heap Fragmentation]]"
hu INTL_FREE_MEMORY "[[Free Memory]]"
hu INTL_LAST_OVER_THE_AIR "[[Last OTA]]"
it INTL_DEVICE_STATUS "Stato del dispositivo"
it INTL_ERROR "Errore"
it INTL_NUMBER_OF_MEASUREMENTS "Numero di misurazioni"
it INTL_TIME_SENDING_MS "Tempo impiegato per l'invio"
it INTL_DATA_SEND_RETURN_CODE "[[Data Send Return]]"
it INTL_UPTIME "[[Uptime]]"
it INTL_RESET_REASON "[[Reset Reason]]"
it INTL_HEAP_FRAGMENTATION "[[Heap Fragmentation]]"
it INTL_FREE_MEMORY "[[Free Memory]]"
it INTL_LAST_OVER_THE_AIR "[[Last OTA]]"
jp INTL_DEVICE_STATUS "デバイスの状態"
jp INTL_ERROR "エラーのみ"
jp INTL_NUMBER_OF_MEASUREMENTS "測定回数"
jp INTL_TIME_SENDING_MS "アップロードにかかった時間"
jp INTL_DATA_SEND_RETURN_CODE "[[Data Send Return]]"
jp INTL_UPTIME "[[Uptime]]"
jp INTL_RESET_REASON "[[Reset Reason]]"
jp INTL_HEAP_FRAGMENTATION "[[Heap Fragmentation]]"
jp INTL_FREE_MEMORY "[[Free Memory]]"
jp INTL_LAST_OVER_THE_AIR "[[Last OTA]]"
lt INTL_DEVICE_STATUS "Įrenginio būsena"
lt INTL_ERROR "tik klaidos"
lt INTL_NUMBER_OF_MEASUREMENTS "Matavimų skaičius"
lt INTL_TIME_SENDING_MS "Įkėlimo laikas"
lt INTL_DATA_SEND_RETURN_CODE "[[Data Send Return]]"
lt INTL_UPTIME "[[Uptime]]"
lt INTL_RESET_REASON "[[Reset Reason]]"
lt INTL_HEAP_FRAGMENTATION "[[Heap Fragmentation]]"
lt INTL_FREE_MEMORY "[[Free Memory]]"
lt INTL_LAST_OVER_THE_AIR "[[Last OTA]]"
lu INTL_DEVICE_STATUS "Apparat Status"
lu INTL_ERROR "fehler"
lu INTL_NUMBER_OF_MEASUREMENTS "Zuel vu Mesuren"
lu INTL_TIME_SENDING_MS "Dauer vu Mesureniwerdroung"
lu INTL_DATA_SEND_RETURN_CODE "[[Data Send Return]]"
lu INTL_UPTIME "[[Uptime]]"
lu INTL_RESET_REASON "[[Reset Reason]]"
lu INTL_HEAP_FRAGMENTATION "[[Heap Fragmentation]]"
lu INTL_FREE_MEMORY "[[Free Memory]]"
lu INTL_LAST_OVER_THE_AIR "[[Last OTA]]"
lv INTL_DEVICE_STATUS "Ierīces statuss"
lv INTL_ERROR "tikai kļūdas"
lv INTL_NUMBER_OF_MEASUREMENTS "Mērījumu skaits"
lv INTL_TIME_SENDING_MS "Laiks, kas pavadīts, augšupielādējot"
lv INTL_DATA_SEND_RETURN_CODE "[[Data Send Return]]"
lv INTL_UPTIME "[[Uptime]]"
lv INTL_RESET_REASON "[[Reset Reason]]"
lv INTL_HEAP_FRAGMENTATION "[[Heap Fragmentation]]"
lv INTL_FREE_MEMORY "[[Free Memory]]"
lv INTL_LAST_OVER_THE_AIR "[[Last OTA]]"
nl INTL_DEVICE_STATUS "Apparaatstatus"
nl INTL_ERROR "enkel foutmeldingen"
nl INTL_NUMBER_OF_MEASUREMENTS "Aantal metingen"
nl INTL_TIME_SENDING_MS "Tijdsduur opsturen metingen"
nl INTL_DATA_SEND_RETURN_CODE "Gegevens versturen Return Code"
nl INTL_UPTIME "Uptime"
nl INTL_RESET_REASON "Reden herstart"
nl INTL_HEAP_FRAGMENTATION "Heap fragmentatie"
nl INTL_FREE_MEMORY "Vrij geheugen"
nl INTL_LAST_OVER_THE_AIR "Laatste OTA"
pl INTL_DEVICE_STATUS "Stan urządzenia"
pl INTL_ERROR "Błędy"
pl INTL_NUMBER_OF_MEASUREMENTS "Liczba pomiarów"
pl INTL_TIME_SENDING_MS "Czas spędzony na wysyłce"
pl INTL_DATA_SEND_RETURN_CODE "[[Data Send Return]]"
pl INTL_UPTIME "[[Uptime]]"
pl INTL_RESET_REASON "[[Reset Reason]]"
pl INTL_HEAP_FRAGMENTATION "[[Heap Fragmentation]]"
pl INTL_FREE_MEMORY "[[Free Memory]]"
pl INTL_LAST_OVER_THE_AIR "[[Last OTA]]"
pt INTL_DEVICE_STATUS "Estado do dispositivo"
pt INTL_ERROR "erro"
pt INTL_NUMBER_OF_MEASUREMENTS "Quantidade de medições"
pt INTL_TIME_SENDING_MS "Duração da transmissão das medições"
pt INTL_DATA_SEND_RETURN_CODE "[[Data Send Return]]"
pt INTL_UPTIME "[[Uptime]]"
pt INTL_RESET_REASON "[[Reset Reason]]"
pt INTL_HEAP_FRAGMENTATION "[[Heap Fragmentation]]"
pt INTL_FREE_MEMORY "[[Free Memory]]"
pt INTL_LAST_OVER_THE_AIR "[[Last OTA]]"
ro INTL_DEVICE_STATUS "Starea dispozitivului"
ro INTL_ERROR "numai erori"
ro INTL_NUMBER_OF_MEASUREMENTS "Număr de măsurători"
ro INTL_TIME_SENDING_MS "Timp petrecut la încărcare"
ro INTL_DATA_SEND_RETURN_CODE "[[Data Send Return]]"
ro INTL_UPTIME "[[Uptime]]"
ro INTL_RESET_REASON "[[Reset Reason]]"
ro INTL_HEAP_FRAGMENTATION "[[Heap Fragmentation]]"
ro INTL_FREE_MEMORY "[[Free Memory]]"
ro INTL_LAST_OVER_THE_AIR "[[Last OTA]]"
rs INTL_DEVICE_STATUS "Status uređaja"
rs INTL_ERROR "greške"
rs INTL_NUMBER_OF_MEASUREMENTS "Broj merenja"
rs INTL_TIME_SENDING_MS "Vreme utrošeno za slanje"
rs INTL_DATA_SEND_RETURN_CODE "[[Data Send Return]]"
rs INTL_UPTIME "[[Uptime]]"
rs INTL_RESET_REASON "[[Reset Reason]]"
rs INTL_HEAP_FRAGMENTATION "[[Heap Fragmentation]]"
rs INTL_FREE_MEMORY "[[Free Memory]]"
rs INTL_LAST_OVER_THE_AIR "[[Last OTA]]"
ru INTL_DEVICE_STATUS "Состояние устройства"
ru INTL_ERROR "только ошибки"
ru INTL_NUMBER_OF_MEASUREMENTS "Количество измерений"
ru INTL_TIME_SENDING_MS "Время, потраченное на отправку"
ru INTL_DATA_SEND_RETURN_CODE "[[Data Send Return]]"
ru INTL_UPTIME "[[Uptime]]"
ru INTL_RESET_REASON "[[Reset Reason]]"
ru INTL_HEAP_FRAGMENTATION "[[Heap Fragmentation]]"
ru INTL_FREE_MEMORY "[[Free Memory]]"
ru INTL_LAST_OVER_THE_AIR "[[Last OTA]]"
se INTL_DEVICE_STATUS "Enhetsstatus"
se INTL_ERROR "error"
se INTL_NUMBER_OF_MEASUREMENTS "Antal mätningar"
se INTL_TIME_SENDING_MS "Tid som skickas i att skicka"
se INTL_DATA_SEND_RETURN_CODE "[[Data Send Return]]"
se INTL_UPTIME "[[Uptime]]"
se INTL_RESET_REASON "[[Reset Reason]]"
se INTL_HEAP_FRAGMENTATION "[[Heap Fragmentation]]"
se INTL_FREE_MEMORY "[[Free Memory]]"
se INTL_LAST_OVER_THE_AIR "[[Last OTA]]"
si INTL_DEVICE_STATUS "Stanje naprave"
si INTL_ERROR "samo napake"
si INTL_NUMBER_OF_MEASUREMENTS "Število meritev"
si INTL_TIME_SENDING_MS "Čas, porabljen za nalaganje"
si INTL_DATA_SEND_RETURN_CODE "[[Data Send Return]]"
si INTL_UPTIME "[[Uptime]]"
si INTL_RESET_REASON "[[Reset Reason]]"
si INTL_HEAP_FRAGMENTATION "[[Heap Fragmentation]]"
si INTL_FREE_MEMORY "[[Free Memory]]"
si INTL_LAST_OVER_THE_AIR "[[Last OTA]]"
sk INTL_DEVICE_STATUS "Stav zariadenia"
sk INTL_ERROR "chyba"
sk INTL_NUMBER_OF_MEASUREMENTS "Počet meraní"
sk INTL_TIME_SENDING_MS "Trvanie odosielania dát"
sk INTL_DATA_SEND_RETURN_CODE "[[Data Send Return]]"
sk INTL_UPTIME "[[Uptime]]"
sk INTL_RESET_REASON "[[Reset Reason]]"
sk INTL_HEAP_FRAGMENTATION "[[Heap Fragmentation]]"
sk INTL_FREE_MEMORY "[[Free Memory]]"
sk INTL_LAST_OVER_THE_AIR "[[Last OTA]]"
tr INTL_DEVICE_STATUS "Cihaz durumu"
tr INTL_ERROR "hatalar"
tr INTL_NUMBER_OF_MEASUREMENTS "Ölçümlerin sayısı"
tr INTL_TIME_SENDING_MS "Göndermede harcanan süre"
tr INTL_DATA_SEND_RETURN_CODE "[[Data Send Return]]"
tr INTL_UPTIME "[[Uptime]]"
tr INTL_RESET_REASON "[[Reset Reason]]"
tr INTL_HEAP_FRAGMENTATION "[[Heap Fragmentation]]"
tr INTL_FREE_MEMORY "[[Free Memory]]"
tr INTL_LAST_OVER_THE_AIR "[[Last OTA]]"
ua INTL_DEVICE_STATUS "стан пристрою"
ua INTL_ERROR "лише помилки"
ua INTL_NUMBER_OF_MEASUREMENTS "Кількість вимірювань"
ua INTL_TIME_SENDING_MS "Час, витрачений на відправлення"
ua INTL_DATA_SEND_RETURN_CODE "[[Data Send Return]]"
ua INTL_UPTIME "[[Uptime]]"
ua INTL_RESET_REASON "[[Reset Reason]]"
ua INTL_HEAP_FRAGMENTATION "[[Heap Fragmentation]]"
ua INTL_FREE_MEMORY "[[Free Memory]]"
ua INTL_LAST_OVER_THE_AIR "[[Last OTA]]"
de INTL_REACHABLE "erreichbar"
nl INTL_REACHABLE "bereikbaar"
de INTL_YES "Ja"
de INTL_NO "Nein"
en INTL_YES "Yes"
en INTL_NO "No"
nl INTL_YES "Ja"
nl INTL_NO "Nee"
EOT
